<?php

namespace AppBundle\Repository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAnswerVote($postId){

        //on instancie  la variable qb et on donne un alias plus court "a"
        $qb = $this->createQueryBuilder("a");
        $qb->select("SUM(s.vote) as score, a.id, a.createdAt, a.text,
         auteur.name as auteurNom, auteur.firstName as auteurPrenom, auteur.email as auteurEmail,auteur.id as auteurId")
            ->innerJoin("a.votes","s")
            ->innerJoin("a.author","auteur")
            ->where("a.post=:postId")
            ->groupBy("a.id")
            ->orderBy("score", 'DESC')
            ->setParameter("postId", $postId);

        // dump (le var_dump de symfony), getDQL retourne un format SQL
        dump($qb->getDQL());

        //on retourne une méthode qui représente les requêtes créées plus haut et l'execute
        return $qb->getQuery()->getArrayResult();

    }

}
