<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function getPostsGroupeByYear(){
        //on instancie $qb et on lui donne un alias
        $qb = $this->createQueryBuilder("p");
        // mon ordre SQL façon doctrine
        $qb->select("YEAR(p.createdAt) as yearPublished, COUNT(p.id) as numberOfPosts")
            ->groupBy("yearPublished");

        return $qb->getQuery()->getArrayResult();
    }


    public function getPostByYear($annee){
        //on instancie $qb et on lui donne un alias
        $qb = $this->createQueryBuilder("p");
        //mon ordre SQL en mode doctrine
        $qb->select("p")
            ->where("YEAR(p.createdAt)=:year")//YEAR utilise OROCRM qui récupère l'année de la DateTime de createdAt
            ->setParameter("year", $annee);

        return $qb->getQuery()->getResult();

    }

    public function getPostsGroupeBythemeID($idTheme){
        //on instancie $qb et on lui donne un alias
        $qb = $this->createQueryBuilder("p");
        // mon ordre SQL façon doctrine
        $qb->select("p.title")
            ->where("p.theme=:idTheme")
            ->setParameter("idTheme", $idTheme);

        return $qb->getQuery()->getArrayResult();
    }
}
