<?php

namespace AppBundle\Repository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllTheme(){
        //on instancie  la variable qb et on donne un alias plus court "t"
        $qb = $this->createQueryBuilder("t");
        // des ordres SQL mais sur les entities, UPPER met en majuscule le resultat de t.name
       // $qb->select("t.id, UPPER(t.name) as name");
        //le select représente : "SELECT t.name, count(p) as numberOfPosts FROM AppBundle\Entity\Theme t INNER JOIN t.posts p GROUP BY t.id"
        // je veux afficher le nom du theme et le nombre de post grace à l'attibut $posts et le résultat je le regroupe par ID
        $qb->select("t.name, count(p) as numberOfPosts, t.slug")
            ->innerJoin("t.posts", "p")
            ->groupBy("t.slug");

        // dump (le var_dump de symfony), getDQL retourne un format SQL
        dump($qb->getDQL());

        //on retourne une méthode qui représente les requêtes créées plus haut et l'execute
        return $qb->getQuery();
    }
}
