<?php

namespace AppBundle\Repository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{

    public function getVoteByAuthorAndbyAnswer($answerId, $userId)
    {

        //on instancie  la variable qb et on donne un alias plus court "v"
        $qb = $this->createQueryBuilder("v");
        $qb->select("v.vote as vote, v.id as id")
            ->where("v.author=:userId")
            ->andWhere("v.answer=:answerId")
        ->setParameter("answerId", $answerId)
        ->setParameter("userId", $userId);

        dump($qb->getDQL());

        return $qb->getQuery()->getArrayResult();
    }

}
