app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_login_check:
  path: /admin/login-check

admin_logout:
  path: admin/logout

author_login_check:
  path: /author/login-check

author_logout:
  path: author/logout
